version: "3.8"

services:
  db:
    image: postgres:15
    container_name: person_service
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgresDb
      POSTGRES_USER: person
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "postgresDb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

